module.exports = {
	NODE_ENV: "development",
	MONGO_URI: ``,
	STRIPE_PUBLICABLE_KEY: "",
	STRIPE_PUBLICABLE_KEY: ``,
	FACEBOOK_APP_ID: ``,
	FACEBOOK_APP_SECRET: ``,
	SECRET_KEY: ``,
	FRONTEND_URL: ``,
	FRONTEND_DASHBOARD_URL: ``,
	ACCOUNTKIT_SECRET: ``,
	AWS_ACCESS_KEY_ID: ``,
	AWS_ACCESS_KEY_SECRET: ``
};
