module.exports = {
	MONGO_URI: process.env.MONGO_URI,
	STRIPE_PUBLICABLE_KEY: process.env.STRIPE_PUBLICABLE_KEY,
	STRIPE_SECRETY_KEY: process.env.STRIPE_SECRETY_KEY,
	FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
	FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
	SECRET_KEY: process.env.SECRET_KEY,
	FRONTEND_URL: process.env.FRONTEND_URL,
	ACCOUNTKIT_SECRET: process.env.ACCOUNTKIT_SECRET,
	AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
	FRONTEND_DASHBOARD_URL: process.env.FRONTEND_DASHBOARD_URL,
	AWS_ACCESS_KEY_SECRET: process.env.AWS_ACCESS_KEY_SECRET
};
